// SPDX-License-Identifier: GPL-2.0+
// Umbrella header. Every archive format that used to be declared here now
// lives in its own lib-<format>.h / lib-<format>.c pair; this header just
// re-exports them so existing includers keep working unchanged.
#ifndef LIB_NINTENDO_ARCHIVES_H
#define LIB_NINTENDO_ARCHIVES_H 1

#include "types.h"
#include "lib-nintendo.h"

#include "lib-xpck.h"
#include "lib-ztab.h"
#include "lib-mdr.h"
#include "lib-xtd.h"
#include "lib-xmd.h"
#include "lib-pfctex.h"
#include "lib-pvol.h"
#include "lib-stpk.h"
#include "lib-f9res.h"
#include "lib-zlarc.h"
#include "lib-gar.h"
#include "lib-mkgpdxpac.h"
#include "lib-tmpk.h"
#include "lib-nxarc.h"
#include "lib-apak.h"
#include "lib-pkz.h"
#include "lib-vibs.h"
#include "lib-pgdat.h"
#include "lib-wta.h"
#include "lib-gfpak.h"
#include "lib-gf3ds.h"
#include "lib-opoona.h"
#include "lib-monster4x4.h"
#include "lib-magma.h"
#include "lib-thevoice.h"
#include "lib-dogisland.h"
#include "lib-muramasa.h"
#include "lib-redsteel2.h"
#include "lib-zackwiki.h"
#include "lib-mtmob.h"
#include "lib-bars.h"
#include "lib-fsb.h"
#include "lib-cspak.h"
#include "lib-sbt.h"
#include "lib-gds.h"
#include "lib-chx.h"
#include "lib-mapbad.h"
#include "lib-txd.h"
#include "lib-ideimg.h"
#include "lib-collpak.h"
#include "lib-agr.h"
#include "lib-bam.h"
#include "lib-csfnt.h"
#include "lib-cscsi.h"
#include "lib-nlgdict.h"
#include "lib-nlg-lm.h"
#include "lib-txtg.h"
#include "lib-romfs.h"
#include "lib-xtx.h"
#include "lib-tvol.h"
#include "lib-mtxt.h"
#include "lib-sir0.h"
#include "lib-ptlg.h"
#include "lib-g1t.h"
#include "lib-zdat.h"
#include "lib-one.h"
#include "lib-pers.h"
#include "lib-camtexbank.h"
#include "lib-nus3audio.h"
#include "lib-ndcubepac.h"

#endif // LIB_NINTENDO_ARCHIVES_H
