#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0+
# Generate project/src/lib-nlg-names.inc from KillzXGaming/NextLevelLibrary
# Hashes/*.txt (MIT License, Copyright (c) 2017-2018 Syroot -- see CREDITS.md).
#
# Faithful port of NextLevelLibrary.Hashing.LoadHashes: every non-empty line
# contributes its as-is hash and its lowercased hash, plus one entry per '/'
# separated path component (component hash -> full string). First entry wins
# on collision, matching Dictionary.ContainsKey guards upstream. The bip01
# generated patterns from LoadHashes() are reproduced verbatim.
#
# Usage: python3 scripts/gen_nlg_names.py HashesDir project/src/lib-nlg-names.inc
import sys


def nlg_hash(name):
    h = -1
    for ch in name.encode("ascii", "replace"):
        h = (h * 33 + ch) & 0xFFFFFFFF
    return h & 0xFFFFFFFF


def c_escape(s):
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "")


def main(hashes_dir, out_path):
    strings = []
    for fn in ("FileNames.txt", "BoneNames.txt", "MaterialNames.txt",
               "ScriptStrings.txt", "Misc.txt"):
        with open("%s/%s" % (hashes_dir, fn), encoding="utf-8-sig") as f:
            for line in f.read().split("\n"):
                s = line.rstrip("\r")
                if s == "":
                    continue
                strings.append(s)
    for i in range(20):
        strings.append("bip01_rarm_bone%02d_exp" % i)
    for i in range(20):
        strings.append("bip01_tail%02d_exp" % i)
    for i in range(20):
        strings.append("bip01_crown%02d_exp" % i)
    for i in range(20):
        strings.append("bip01_tongue%02d_exp" % i)
    for i in range(40):
        strings.append("bip01_larmdigit%02d_exp" % i)
    for i in range(40):
        strings.append("bip01_rarmdigit%02d_exp" % i)

    table = {}  # hash -> full string, first wins
    for s in strings:
        for variant in (s, s.lower()):
            h = nlg_hash(variant)
            if h not in table:
                table[h] = s
        for comp in s.split("/"):
            h = nlg_hash(comp)
            if h not in table:
                table[h] = s

    names = sorted(set(table.values()))
    name_idx = {n: i for i, n in enumerate(names)}
    entries = sorted((h, name_idx[s]) for h, s in table.items())

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("// SPDX-License-Identifier: GPL-2.0+\n")
        f.write("// GENERATED FILE -- DO NOT EDIT.\n")
        f.write("// Generated by scripts/gen_nlg_names.py from\n")
        f.write("// KillzXGaming/NextLevelLibrary Hashes/*.txt (MIT, see CREDITS.md),\n")
        f.write("// a faithful port of NextLevelLibrary.Hashing.LoadHashes.\n")
        f.write("static const char *const nlg_name_str[%d] = {\n" % len(names))
        for n in names:
            f.write('"%s",\n' % c_escape(n))
        f.write("};\n")
        f.write("typedef struct { u32 hash; u32 name; } nlg_name_ent_t;\n")
        f.write("static const nlg_name_ent_t nlg_name_tab[%d] = {\n" % len(entries))
        for h, i in entries:
            f.write("{0x%08xu,%u},\n" % (h, i))
        f.write("};\n")
    print("wrote %s: %d strings, %d hash entries" % (out_path, len(names), len(entries)))


main(sys.argv[1], sys.argv[2])
